### ISSUE TITLE
Initial project feedback

### ISSUE THREAD

**Issue by thedarkjester** [akerbabber/blockchain-developer-bootcamp-final-project#1]
Hello, do you perhaps have a demo video that has been uploaded so that we can view it. Looking at the deployed application, I seemed to be getting a lot of errors (javascript one) when trying to interact with it.

The faucet triggers ok. but everything else doesn't seem to work. I tried the LINK token as well as all the ones in your provided txt file.

![image](https://user-images.githubusercontent.com/3957173/152701921-ed20affb-8ec9-4f6b-85b8-47914a204b89.png)

**Comment by akerbabber** [comment]
Hello, I have worked through this week to fix the UI. Now it should work as intended.
The link to the video recording is now on README.md.

**Comment by akerbabber** [comment]
Closed.
